// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"github.com/FFFcomewhere/issue-example/app/usercenter/rpc/internal/logic"
	"github.com/FFFcomewhere/issue-example/app/usercenter/rpc/internal/svc"
	"github.com/FFFcomewhere/issue-example/app/usercenter/rpc/types/builder"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	builder.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *builder.RegisterReq) (*builder.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *builder.LoginReq) (*builder.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) GetUserInfo(ctx context.Context, in *builder.GetUserInfoReq) (*builder.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserServer) GenerateToken(ctx context.Context, in *builder.GenerateTokenReq) (*builder.GenerateTokenResp, error) {
	l := logic.NewGenerateTokenLogic(ctx, s.svcCtx)
	return l.GenerateToken(in)
}
