// Code generated by goctl. DO NOT EDIT.
package types

type IssueInfo struct {
	Issueid       int64  `json:"issueid"`
	IssueName     string `json:"issueName"`
	UpdateTime    string `json:"updateTime"`
	UserName      string `json:"userName"`
	TagName       string `json:"tagName"`
	MilestoneName string `json:"milestoneName"`
}

type CommentInfo struct {
	Commentid  int64  `json:"commentid"`
	UpdateTime string `json:"updateTime"`
	UserName   string `json:"userName"`
	Content    string `json:"content"`
}

type IssueReq struct {
	Page     int64 `json:"page"`     //页码
	PageSize int64 `json:"pageSize"` //当前页面显示的issue数量
}

type IssueResp struct {
	List []IssueInfo `json:"list"`
}

type IssueNewReq struct {
	Name          string `json:"name"`
	UserName      string `json:"userName"`
	TagName       string `json:"tagName"`
	MilestoneName string `json:"milestoneName"`
}

type IssueNewResp struct {
}

type IssueSignalReq struct {
	Issueid         int64  `json:"issueid"`
	ReName          string `json:"reName"`          //重命名标题
	ReTag           string `json:"reTag"`           //重命名标签
	ReMilestone     string `json:"reMilestone"`     //重命名里程碑
	IfDelete        bool   `json:"ifDelete"`        //是否删除提案
	AddComment      string `json:"addComment"`      //添加评论
	DeleteCommentid int64  `json:"deleteCommentid"` //被删除评论的id
	UpdateCommentid int64  `json:"updateCommentid"` //被修改评论的id
	UpdateComment   string `json:"updateComment"`   //修改评论
}

type IssueSignalResp struct {
	Issue       IssueInfo     `json:"issue"`       //提案信息
	CommentList []CommentInfo `json:"commentList"` //页面显示的评论信息
}

type MilestoneInfo struct {
	Milestoneid int64  `json:"milestoneid"`
	Name        string `json:"name"`
	UpdateTime  string `json:"updateTime"`
}

type MilestoneReq struct {
	Page     int64 `json:"page"`     //页码
	PageSize int64 `json:"pageSize"` //当前页面显示的milestone数量
}

type MilestoneResp struct {
	List []MilestoneInfo `json:"list"`
}

type MilestoneNewReq struct {
	Name string `json:"name"`
}

type MilestoneNewResp struct {
}

type MilestoneSignalReq struct {
	Milestoneid int64  `json:"milestoneid"`
	ReName      string `json:"reName"`
	IfDelete    bool   `json:"ifDelete"`
}

type MilestoneSignalResp struct {
	Milestone MilestoneInfo `json:"milestone"`
	IssueList []IssueInfo   `json:"issueList"`
}

type TagInfo struct {
	Tagid int64  `json:"tagid"`
	Name  string `json:"name"`
}

type TagReq struct {
	Page     int64 `json:"page"`     //页码
	PageSize int64 `json:"pageSize"` //当前页面显示的tag数量
}

type TagResp struct {
	List []TagInfo `json:"list"`
}

type TagNewReq struct {
	Name string `json:"name"`
}

type TagNewResp struct {
}

type TagSignalReq struct {
	Name     string `json:"name"`
	ReName   string `json:"reName"`
	IfDelete bool   `json:"ifDelete"`
}

type TagSignalResp struct {
	Tag       TagInfo     `json:"tag"`
	IssueList []IssueInfo `json:"issueList"`
}

type IssueStateInfo struct {
	Issueid        int64 `json:"issueid"`
	AddTagid       int64 `json:"addTagid"`
	DeleteTagid    int64 `json:"deleteTagid"`
	AddCommentid   int64 `json:"addCommentid"`
	DeleteComentid int64 `json:"deleteComentid"`
}

type IssueStatePushReq struct {
	IfSubscription bool `json:"ifSubscription"`
}

type IssueStatePushResp struct {
	IssueState IssueStateInfo `json:"issueState"`
}

type IssueSearchReq struct {
	Keyword string `json:"keyword"` //搜索的关键词
}

type IssueSearchResp struct {
	List []IssueInfo `json:"list"` //返回的issue列表
}
