// Code generated by goctl. DO NOT EDIT.
package types

type UserInfo struct {
	Userid   int64  `json:"userid"`
	Mobile   string `json:"mobile"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type GetUserInfoReq struct {
	Userid   int64  `json:"userid"`
	Mobile   string `json:"mobile"`
	Username string `json:"username"`
}

type GetUserInfoResp struct {
	Userid   int64  `json:"userid"`
	Mobile   string `json:"mobile"`
	Username string `json:"username"`
}
