// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/FFFcomewhere/issue-example/common/globalkey"
	"github.com/FFFcomewhere/issue-example/common/xerr"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	issueFieldNames          = builder.RawFieldNames(&Issue{})
	issueRows                = strings.Join(issueFieldNames, ",")
	issueRowsExpectAutoSet   = strings.Join(stringx.Remove(issueFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	issueRowsWithPlaceHolder = strings.Join(stringx.Remove(issueFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheIssueExampleIssueIdPrefix = "cache:issueExample:issue:id:"
)

type (
	issueModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Issue) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Issue, error)
		Update(ctx context.Context, session sqlx.Session, data *Issue) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Issue) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultIssueModel struct {
		sqlc.CachedConn
		table string
	}

	Issue struct {
		Id          int64     `db:"id"`
		CreateTime  time.Time `db:"create_time"`
		UpdateTime  time.Time `db:"update_time"`
		DeleteTime  time.Time `db:"delete_time"`
		DelState    int64     `db:"del_state"`
		Version     int64     `db:"version"`     // 版本号
		Name        string    `db:"name"`        // 提案名称
		Userid      int64     `db:"userid"`      // 提案发起者id
		Tagid       int64     `db:"tagid"`       // 标签id
		Milestoneid int64     `db:"milestoneid"` // 里程碑id
	}
)

func newIssueModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultIssueModel {
	return &defaultIssueModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`issue`",
	}
}

func (m *defaultIssueModel) Insert(ctx context.Context, session sqlx.Session, data *Issue) (sql.Result, error) {
	data.DeleteTime = time.Unix(0, 0)
	issueExampleIssueIdKey := fmt.Sprintf("%s%v", cacheIssueExampleIssueIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, issueRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Name, data.Userid, data.Tagid, data.Milestoneid)
		}
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Name, data.Userid, data.Tagid, data.Milestoneid)
	}, issueExampleIssueIdKey)
}

func (m *defaultIssueModel) FindOne(ctx context.Context, id int64) (*Issue, error) {
	issueExampleIssueIdKey := fmt.Sprintf("%s%v", cacheIssueExampleIssueIdPrefix, id)
	var resp Issue
	err := m.QueryRowCtx(ctx, &resp, issueExampleIssueIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", issueRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultIssueModel) Update(ctx context.Context, session sqlx.Session, data *Issue) (sql.Result, error) {
	issueExampleIssueIdKey := fmt.Sprintf("%s%v", cacheIssueExampleIssueIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, issueRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Name, data.Userid, data.Tagid, data.Milestoneid, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Name, data.Userid, data.Tagid, data.Milestoneid, data.Id)
	}, issueExampleIssueIdKey)
}

func (m *defaultIssueModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Issue) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	issueExampleIssueIdKey := fmt.Sprintf("%s%v", cacheIssueExampleIssueIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, issueRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Name, data.Userid, data.Tagid, data.Milestoneid, data.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Name, data.Userid, data.Tagid, data.Milestoneid, data.Id, oldVersion)
	}, issueExampleIssueIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return xerr.NewErrCode(xerr.DB_UPDATE_AFFECTED_ZERO_ERROR)
	}

	return nil
}

func (m *defaultIssueModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	issueExampleIssueIdKey := fmt.Sprintf("%s%v", cacheIssueExampleIssueIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, issueExampleIssueIdKey)
	return err
}

func (m *defaultIssueModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheIssueExampleIssueIdPrefix, primary)
}
func (m *defaultIssueModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", issueRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultIssueModel) tableName() string {
	return m.table
}
