// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/FFFcomewhere/issue-example/common/globalkey"
	"github.com/FFFcomewhere/issue-example/common/xerr"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tagFieldNames          = builder.RawFieldNames(&Tag{})
	tagRows                = strings.Join(tagFieldNames, ",")
	tagRowsExpectAutoSet   = strings.Join(stringx.Remove(tagFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	tagRowsWithPlaceHolder = strings.Join(stringx.Remove(tagFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheIssueExampleTagIdPrefix   = "cache:issueExample:tag:id:"
	cacheIssueExampleTagNamePrefix = "cache:issueExample:tag:name:"
)

type (
	tagModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Tag) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Tag, error)
		FindOneByName(ctx context.Context, name string) (*Tag, error)
		Update(ctx context.Context, session sqlx.Session, data *Tag) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Tag) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultTagModel struct {
		sqlc.CachedConn
		table string
	}

	Tag struct {
		Id         int64     `db:"id"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		DeleteTime time.Time `db:"delete_time"`
		DelState   int64     `db:"del_state"`
		Version    int64     `db:"version"` // 版本号
		Name       string    `db:"name"`    // 标签名称
	}
)

func newTagModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultTagModel {
	return &defaultTagModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`tag`",
	}
}

func (m *defaultTagModel) Insert(ctx context.Context, session sqlx.Session, data *Tag) (sql.Result, error) {
	data.DeleteTime = time.Unix(0, 0)
	issueExampleTagIdKey := fmt.Sprintf("%s%v", cacheIssueExampleTagIdPrefix, data.Id)
	issueExampleTagNameKey := fmt.Sprintf("%s%v", cacheIssueExampleTagNamePrefix, data.Name)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, tagRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Name)
		}
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Name)
	}, issueExampleTagIdKey, issueExampleTagNameKey)
}

func (m *defaultTagModel) FindOne(ctx context.Context, id int64) (*Tag, error) {
	issueExampleTagIdKey := fmt.Sprintf("%s%v", cacheIssueExampleTagIdPrefix, id)
	var resp Tag
	err := m.QueryRowCtx(ctx, &resp, issueExampleTagIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", tagRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTagModel) FindOneByName(ctx context.Context, name string) (*Tag, error) {
	issueExampleTagNameKey := fmt.Sprintf("%s%v", cacheIssueExampleTagNamePrefix, name)
	var resp Tag
	err := m.QueryRowIndexCtx(ctx, &resp, issueExampleTagNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? and del_state = ? limit 1", tagRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name, globalkey.DelStateNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTagModel) Update(ctx context.Context, session sqlx.Session, data *Tag) (sql.Result, error) {
	issueExampleTagIdKey := fmt.Sprintf("%s%v", cacheIssueExampleTagIdPrefix, data.Id)
	issueExampleTagNameKey := fmt.Sprintf("%s%v", cacheIssueExampleTagNamePrefix, data.Name)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tagRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Name, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Name, data.Id)
	}, issueExampleTagIdKey, issueExampleTagNameKey)
}

func (m *defaultTagModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Tag) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	issueExampleTagIdKey := fmt.Sprintf("%s%v", cacheIssueExampleTagIdPrefix, data.Id)
	issueExampleTagNameKey := fmt.Sprintf("%s%v", cacheIssueExampleTagNamePrefix, data.Name)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, tagRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Name, data.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Name, data.Id, oldVersion)
	}, issueExampleTagIdKey, issueExampleTagNameKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return xerr.NewErrCode(xerr.DB_UPDATE_AFFECTED_ZERO_ERROR)
	}

	return nil
}

func (m *defaultTagModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	issueExampleTagIdKey := fmt.Sprintf("%s%v", cacheIssueExampleTagIdPrefix, id)
	issueExampleTagNameKey := fmt.Sprintf("%s%v", cacheIssueExampleTagNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, issueExampleTagIdKey, issueExampleTagNameKey)
	return err
}

func (m *defaultTagModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheIssueExampleTagIdPrefix, primary)
}
func (m *defaultTagModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", tagRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultTagModel) tableName() string {
	return m.table
}
